version: "2"
networks:
    ms-net:
        driver: bridge  
services:
    mongo-db:
        image : mongo
        networks:
            - ms-net
        container_name: mongo-db
        volumes:
            - /home/barry/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
    mongo-client:
        image: mongoclient/mongoclient
        ports:
        - 3030:3000
        environment:
          - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo-db:27017
        links:
          - mongo-db
    inventory-management:
        image: pedrovcruzeiro/inventory-management:0.0.6
        networks:
            - ms-net
        ports:
            - 9080:8080
            - 9090:9090
        links:
            - mongo-db
        depends_on:
            - mongo-db