spring:
  application:
    name: inventory-management
  boot:
    admin:
      client:
        enabled: true
        url: http://localhost:9090
  data:
    mongodb:
      uri: mongodb://mongo-db:27017/dev